inherit: true

checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php:
      version: 5.5.9
  tests:
    override:
      -
        command: vendor/phpspec/phpspec/bin/phpspec run spec --no-interaction
        coverage:
          file: 'coverage.xml'
          format: php-clover
      - phpenv global 5.6.9 && vendor/phpspec/phpspec/bin/phpspec run spec --no-interaction
      - phpenv global 7.0.0 && vendor/phpspec/phpspec/bin/phpspec run spec --no-interaction

before_commands:
  - composer self-update
  - composer install

filter:
  paths: [ 'src/*' ]

